// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlq3PatrdX4UryCIxskTcAa95f1EFnejk',
    appId: '1:440430481154:web:e335b97d1ac61c58dc7c1b',
    messagingSenderId: '440430481154',
    projectId: 'supercalculadora-52c51',
    authDomain: 'supercalculadora-52c51.firebaseapp.com',
    storageBucket: 'supercalculadora-52c51.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAte4ciuWdd-2g4VGuYvj8z4PsYwYX3GfU',
    appId: '1:440430481154:android:411ac6cb5512a564dc7c1b',
    messagingSenderId: '440430481154',
    projectId: 'supercalculadora-52c51',
    storageBucket: 'supercalculadora-52c51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV81n1OG76YPK8aOxL55wuN30OvZO1CMY',
    appId: '1:440430481154:ios:e92137b743d48f4ddc7c1b',
    messagingSenderId: '440430481154',
    projectId: 'supercalculadora-52c51',
    storageBucket: 'supercalculadora-52c51.appspot.com',
    iosBundleId: 'com.example.supcalculadora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV81n1OG76YPK8aOxL55wuN30OvZO1CMY',
    appId: '1:440430481154:ios:ca3e32568d14371bdc7c1b',
    messagingSenderId: '440430481154',
    projectId: 'supercalculadora-52c51',
    storageBucket: 'supercalculadora-52c51.appspot.com',
    iosBundleId: 'com.example.supcalculadora.RunnerTests',
  );
}
